name: Build FFmpeg audio only shared lib

on:
  push:
  pull_request:

jobs:
  linux-pkg:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yasm
      - name: Install ARM64 compiler
        if: env.ARCH == 'arm64'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build
        run: ./build-linux.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-${{ env.ARCH }}
          path: artifacts/
