name: Build FFmpeg audio only shared lib

on:
  push:
  pull_request:

jobs:
  linux-pkg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
    env:
      ARCH: ${{ matrix.arch }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yasm
      - name: Install ARM64 compiler
        if: env.ARCH == 'arm64'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build
        run: ./build_linux.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-${{ env.ARCH }}
          path: build/artifacts/$ffmpeg_${{ env.ARCH }}_linux.tar.gz

  win64-pkg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
    env:
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yasm
      - name: Install MinGW compiler
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mingw-w64
      - name: Build
        run: ./build_windows.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-${{ env.ARCH }}
          path: build/artifacts/ffmpeg_${{ env.ARCH }}_win64.tar.gz
